### PR TITLE
Fixes from from i5MC [WIP]

### PR DESCRIPTION
**Pull request by wesleyvanneck**
sorry @7kasper for some stuff are going to be gone if merging it but hey but we got most things working 👍

so far i need to find a way to make hollograms insvible again :3

note: i can compile it localy but i cant seem to commit strait out of git so i know it works but its just my freaking pc doing wierd

### CODE REVIEW

**Comment by wesleyvanneck** [comment]
screenshot_20180816-182703
screenshot_20180816-182825

**Comment by wesleyvanneck** [comment]
Here is soms prove of whats works so far  i dident test de skulls do

**Comment by 7kasper** [comment]
What... this doesnt seem right. Check the changes. Are you sure you arent trying to override to an old version?

**Comment by wesleyvanneck** [comment]
@7kasper most things come from i5Mc branch from caoli

**Comment by wesleyvanneck** [comment]
@7kasper and the holograms arnt invible if i have free time am going to look in to it

**Comment by wesleyvanneck** [comment]
And what dosnt seem right @7kasper

**Comment by wesleyvanneck** [comment]
am going to import the changes instead

**Pull request closed without merging**
